# Generated by Django 6.1.2 on 2026-10-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("chegada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("chamado", "Chamado"),
                            ("removido", "Removido"),
                        ],
                        db_index=True,
                        default="aguardando",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["chegada_em", "id"],
            },
        ),
        migrations.CreateModel(
            name="Chamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sala", models.CharField(max_length=20)),
                ("medico", models.CharField(max_length=120)),
                ("chamada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chamadas",
                        to="fila.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-chamada_em", "-id"],
            },
        ),
    ]
